#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export STUDENT_MODEL="${STUDENT_MODEL:-Qwen/Qwen3-0.6B}"
export TEACHER_MODEL="${TEACHER_MODEL:-Qwen/Qwen3-4B-Instruct-2507}"
export TRAIN_DATA="${TRAIN_DATA:?Set TRAIN_DATA to the training parquet file}"
export BENCH="${BENCH:-${ROOT}/maestro/eval}"
export OUTPUT_DIR="${OUTPUT_DIR:-${ROOT}/outputs/qwen3_0_6b_$(date +%Y%m%d_%H%M%S)}"
export ACTOR_GPUS_PER_NODE="${ACTOR_GPUS_PER_NODE:-4}"
export TEACHER_GPUS_PER_NODE="${TEACHER_GPUS_PER_NODE:-4}"
export TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-128}"
export PPO_MINI_BATCH_SIZE="${PPO_MINI_BATCH_SIZE:-128}"
export MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-8192}"
export MAESTRO_PDS_ENABLE=1 MAESTRO_PDS_AGGREGATION=paragraph_weighted MAESTRO_PDS_THRESHOLD=0.14 MAESTRO_PDS_WARMUP_TOKENS=128
export MAESTRO_PARAGRAPHS_PER_TAKEOVER=4 MAESTRO_MAX_TAKEOVER_TOKENS=256 MAESTRO_MAX_TAKEOVERS=2 MAESTRO_MAX_TAKEOVERS_BEHAVIOR=stop
export MAESTRO_FAULT_TAKEOVER_QUOTA=1
export MAESTRO_FAULT_REWIND_TO_BOUNDARY=1
export MAESTRO_LINEAR_PDS_BUDGET=1 MAESTRO_PDS_TRIGGER_THRESHOLD=0.14 MAESTRO_PDS_DIFFICULTY_STEP=0.02 MAESTRO_PDS_BASE_PARAGRAPHS=4 MAESTRO_PDS_MAX_PARAGRAPHS=12
exec bash "${ROOT}/scripts/maestro_train_core.sh" "$@"

